### ISSUE TITLE
what does it mean by "turn on any installed DLL mods"?

### ISSUE THREAD

**Issue by opyate** [techiew/EldenRingEacToggler#3]
Hello, thanks for this framework.

The nexus doc says 

> Simply run "toggle_anti_cheat.exe" and it will disable EAC and **turn on any installed DLL mods**.

When I run the toggle, then install new mods into `mods/` folder, do I have to
- re-run the toggle for the new mods to be able to run?
- do nothing, as the new mods will just work?

While I'm here, it might also be worth asking: how do I know if the toggle is active?

Thanks!

**Comment by techiew** [comment]
Yo,
Mods under the mods/ folder will work without retoggling anything, even new ones you just put in. The mods that are referred to in this case are the "mods" in the top level folder, such as EldenModLoader and other mods that have DLLs in the game root folder. The toggler simply adds a _ at the start of any mod DLL names to stop them from loading on game boot.

That's also how you know if the anticheat is toggled without booting - if there are a bunch of files with _ in the name then the anticheat is on and vice versa. But the best way to know for sure is to run the toggler and see what pops up.

**Comment by opyate** [comment]
Thanks for that :)
