### ISSUE TITLE
"inappropriate activity detected" not shown - is EAC disabled?

### ISSUE THREAD

**Issue by Bogdanov89** [techiew/EldenRingEacToggler#6]
Sorry for this beginner question, its my first time modding elden ring.
I just installed Anti-cheat toggler and mod loader and followed the installation but i did not get the "inappropriate activity detected" when i started Elden Ring via steam.

I did run the "toggle_anti_cheat.exe" as admin (windows 10).
Also my elden ring was already configured to start the game in offline mode - i do not know is that perhaps the reason for the message to be missing?

Thanks for helping and making all of this.

**Comment by techiew** [comment]
I think it's probably because it's configured to start in offline mode anyway. Doesn't matter if you don't get the message.
